language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.12
      osx_image: xcode7.3
      dotnet: 1.0.0-rc4-0044771
      
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
