language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-1-003177

solution: ExpressBase.Core.sln
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
