language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 4.6.2
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

solution: ExpressBase.Core.sln
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
